name: Build and Push Angular App Container

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run ESLint
        run: npm run lint

      # - name: Run Tests
      #   run: npm run test

      - name: Build Angular app (production)
        run: npm run build

      - name: Archive build output
        run: |
          mkdir -p drop
          cp -r ./dist/box2box/browser/* ./drop/

      - name: Copy nginx.conf to drop
        run: cp nginx.conf drop/

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: drop
          path: drop/

  container:
    if: github.event_name == 'push' && (startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/heads/dev'))
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: drop
          path: drop

      - name: Build Docker image
        run: |
         

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Push Docker images
        run: |
